export const courses = [
  {
    id: 1,
    type: "course",
    priority: false,
    name: "Kurs Express",
    secondaryTitle: "Prawo jazdy w 3 tygodnie",
    price: "6500 zł",
    length: "16 dni",
    description: "30h teorii + 30h praktyki",
    category: "KATEGORIA B",
    features: [
      "30h wykladów teorii (intensywnie)",
      "30h jazdy z instruktorem",
      "Prawo jazdy w 16 dni",
      "Priorytetowe terminy jazd",
    ],
  },
  {
    id: 2,
    priority: true,
    type: "course",
    name: "Kurs Standardowy",
    secondaryTitle: "Idealny jeśli nie masz pośpiechu",
    price: "4000 zł",
    length: "2 miesiące",
    description: "30h teorii + 30h praktyki",
    category: "KATEGORIA B",
    features: [
      "30h teorii + 30h jazdy praktycznej",
      "Własny plac manewrowy przy ośrodku",
      "Kia Rio — auto egzaminacyjne WORD",
      "Kurs Pierwszej Pomocy w cenie",
      "Rejestrator jazdy — nagranie każdej lekcji",
      "Płatność w ratach 0%",
    ],
  },
  {
    id: 3,
    type: "usluga",
    priority: false,
    name: "Jazda Dodatkowa",
    secondaryTitle: "Dla kursantów potrzebujących więcej praktyki",
    price: "150 zł/h",
    category: "DODATKOWE",
    features: [
      "1 godzina z instruktorem",
      "Dowolny termin",
      "Dla absolwentów i kursantów",
    ],
  },
];
